DOPS-216: Add MM_INSTALL_TYPE=operator
mattermost/mattermost-operator pull request #183
Opened 2020-10-02 13:31 UTC by metanerd

#### Summary
 Sets an environment variable to get an idea of the preferred installation type. 

#### Ticket Link

https://mattermost.atlassian.net/jira/software/projects/DOPS/boards/66/backlog?selectedIssue=DOPS-216

#### Release Note

```release-note
NONE
```

2020-10-02 14:37 UTC, metanerd commented on pkg/mattermost/mattermost.go
> +			Value: "operator",
```suggestion
			Value: "kubernetes",
```

2020-10-02 20:07 UTC, gabrieljackson approved these changes
Looks good!

I did want to check that we want to use `kubernetes` as the value for this though. We have at least two types of kubernetes deployments with helm and the operator. Do we want to be more specific with something like `kubernetes-operator` or something similar?

2020-10-02 22:44 UTC, metanerd commented
@grundleborg ^

2020-10-05 09:43 UTC, grundleborg commented
@gabrieljackson @metanerd making it more specific in that case would be great - you can choose the term (so `kubernetes_operator` is great).

2020-10-06 07:58 UTC, cpanato requested changes
@metanerd can you update the variable name per George request?
otherwise lgtm

2020-10-06 07:59 UTC, metanerd commented on pkg/mattermost/mattermost.go
> +			Value: "kubernetes",
```suggestion
			Value: "kubernetes-operator",
```

2020-10-06 08:06 UTC, cpanato approved these changes

2020-10-06 08:07 UTC, cpanato commented
adding @grundleborg as a reviewer as well since he asks for the change

2020-10-06 08:11 UTC, grundleborg approved these changes
LGTM

2020-10-06 08:24 UTC, merged